version: '3.5'

services:
  database:
    container_name: db_postgres
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data/api-golang
    volumes:
        - api-golang:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
    api-golang: